title:        Rhos y Fedwen
tagline:      'Rhos y Fedwen Primary'
description:  'Building bridges to brighter future'
url:          http://rhosyfedwen.co.uk
version:      1.1.1
author:
  name:       'Rhos y Fedwen'
  email:      'rhosyfedwen@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
