title:        Rhos y Fedwen Primary
tagline:      'Building bridges to brighter future'
description:  'Rhos y Fedwen Primary school caring for children in Rassau, Ebbw Vale.'
url:          http://rhosyfedwen.co.uk
version:      1.1.1
author:
  name:       'Rhos y Fedwen'
  email:      'rhosyfedwen@gmail.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
